taskmanager/main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'

urlpatterns = [
    path('', views.start, name='home'),
    path('timetable', views.week, name='timetable'),
    path('purpose', views.purpose, name='purpose'),

    path('todolist', views.todolist, name='list'),
    path('dell_list/<int:idl>/<int:idt>', views.dell_list, name='dell_list'),
    path('create_list', views.create_list, name='create_list'),

    path('create_task', views.create_task, name='create_task'),
    path('create_purpose', views.create_purpose, name='create_purpose'),

    path('add_task_week/<int:d>', views.add_task, name="add_task_week"),
    path('add_task_list', views.add_task_list, name="add_task_list"),

    path('change_week', views.change_week, name='change_week'),
    path('change_week/del/<int:idd>/<int:it>', views.dell_task, name="dell_task"),

    path('change_purpose/<int:idp>', views.change_purpose, name="change_purpose"),
    path('change_purpose/del/<int:idp>/<int:idt>', views.dell_purpose, name="dell_purpose"),
    path('change_purpose/add/<int:idp>', views.add_task_purpose, name="add_task_purpose")
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

taskmanager/taskmanager/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'main'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

taskmanager/main/models.py
from django.db import models


class Task(models.Model):
    name = models.CharField('Task', max_length=100)
    time = models.TimeField('Time')

    def __str__(self):
        return self.name


class Timetable(models.Model):
    DAY_WEEK = {
        ('Mo', 'Monday'),
        ('Tu', 'Tuesday'),
        ('We', 'Wednesday'),
        ('Th', 'Thursday'),
        ('Fr', 'Friday'),
        ('Sa', 'Saturday'),
        ('Su', 'Sunday')
    }
    name = models.CharField('Day', max_length=2, choices=DAY_WEEK)
    task = models.ManyToManyField(Task)


class Purpose(models.Model):
    name = models.CharField('Name', max_length=100)
    task = models.ManyToManyField(Task)
    start = models.DateTimeField('Start', auto_now_add=True)
    finish = models.DateTimeField('Finish', auto_now_add=True)
    planed = models.DateTimeField('Planed')


class TaskList(models.Model):
    task = models.OneToOneField(Task, on_delete=models.CASCADE)
    data = models.DateField('Data')

taskmanager/main/forms.py
from django.conf import settings
from .models import Task, TaskList, Purpose
from django import forms


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'time']
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите'
            }),
            'time': forms.DateTimeInput(attrs={
                'id': "timepkr",
                'style': "width:100px;float:left;",
                'class': "form-control",
                'placeholder': "HH:MM",
            })
        }


class ListAdd(forms.ModelForm):
    data = forms.DateField(widget=forms.DateInput(format='%d/%m/%Y'), input_formats=settings.DATE_INPUT_FORMATS)
    class Meta:
        model = TaskList
        task = forms.ModelChoiceField(queryset=Task.objects.all(), to_field_name="id")
        fields = ['data', 'task']
        widgets = {
            'data': forms.DateInput(attrs={'placeholder': 'DD-MM-YYYY', 'required': 'required'})
        }


class PurposeForm(forms.ModelForm):
    planed = forms.DateField(widget=forms.DateInput(format='%d/%m/%Y %H:%M'), input_formats=settings.DATE_INPUT_FORMATS)
    class Meta:
        model = Purpose
        task = forms.ModelChoiceField(queryset=Task.objects.all(), to_field_name="id")
        fields = ['name', 'task', 'planed']
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите'
            }),
            'plan': forms.DateTimeInput(attrs={
                'id': "timepkr",
                'style': "width:100px;float:left;",
                'class': "form-control",
                'placeholder': "DD-MM-YYYY HH:MM",
            })
        }

taskmanager/main/views.py
from django.shortcuts import render, redirect
from django.http import Http404
from .models import Task, Timetable, Purpose, TaskList
from .forms import TaskForm, PurposeForm, ListAdd
from datetime import datetime


def start(request):
    return render(request, 'main/start.html')


def create_task(request):
    error = ''
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(request.META.get('HTTP_REFERER'))
        else:
            error = 'The form is not correct'

    form = TaskForm()
    context = {
        'form': form,
        'error': error
    }
    return render(request, 'main/create_task.html', context)


def week(request):
    Monday = Timetable.objects.filter(name__exact='Mo')
    Tuesday = Timetable.objects.filter(name__exact='Tu')
    Wednesday = Timetable.objects.filter(name__exact='We')
    Thursday = Timetable.objects.filter(name__exact='Th')
    Friday = Timetable.objects.filter(name__exact='Fr')
    Saturday = Timetable.objects.filter(name__exact='Sa')
    Sunday = Timetable.objects.filter(name__exact='Su')
    week = (
        Monday, Tuesday, Wednesday, Thursday,
        Friday, Saturday, Sunday
    )
    week_n = (
        'Monday', 'Tuesday', 'Wednesday', 'Thursday',
        'Friday', 'Saturday', 'Sunday'
    )
    return render(request, 'main/week.html', {'title': 'Week', 'week': week, 'week_n': week_n})


def change_week(request):
    Monday = Timetable.objects.filter(name__exact='Mo')
    Tuesday = Timetable.objects.filter(name__exact='Tu')
    Wednesday = Timetable.objects.filter(name__exact='We')
    Thursday = Timetable.objects.filter(name__exact='Th')
    Friday = Timetable.objects.filter(name__exact='Fr')
    Saturday = Timetable.objects.filter(name__exact='Sa')
    Sunday = Timetable.objects.filter(name__exact='Su')
    week = (
        Monday, Tuesday, Wednesday, Thursday,
        Friday, Saturday, Sunday
    )
    week_n = (
        'Monday', 'Tuesday', 'Wednesday', 'Thursday',
        'Friday', 'Saturday', 'Sunday'
    )
    n = (1, 2, 3, 4, 5, 6, 7)
    return render(request, 'main/change_week.html', {'title': 'Week', 'week': week, 'week_n': week_n, 'n': n})


def dell_task(request, idd, it):
    d = Timetable.objects.get(id=idd)
    d.task.remove(Task.objects.get(id=it))
    return redirect(request.META.get('HTTP_REFERER'))


def add_task(request, d):
    if 1 > d < 7:
        raise Http404('Wrong!')
    task = Task.objects.all()
    if request.method == 'POST':
        if request.POST['task']:
            post = request.POST['task']
            day = Timetable.objects.get(id=d)
            day.task.add(Task.objects.get(id=post))

    return render(request, 'main/add_task_week.html', {'title': 'Week', 'task': task})


def todolist(request):
    week = (
        'Mo',
        'Tu',
        'We',
        'Th',
        'Fr',
        'Sa',
        'Su'
    )
    now = datetime.today().strftime('%A')
    day = Timetable.objects.filter(name__exact=week[datetime.today().weekday()])
    task = TaskList.objects.all()
    return render(request, 'main/todolist.html', {'title': 'ToDoList', 'task': task, 'day': day, 'now': now})


def add_task_list(request):
    task = Task.objects.all()
    if request.method == 'POST':
        if request.POST['task']:
            post = request.POST['task']
            TaskList.objects.create(task=Task.objects.get(id=post))

    return render(request, 'main/add_task_list.html', {'title': 'List', 'task': task})


def dell_list(request, idl, idt):
    taskl = TaskList.objects.get(id=idl).delete()
    return redirect(request.META.get('HTTP_REFERER'))


def create_list(request):
    error = ''
    if request.method == 'POST':
        form = ListAdd(request.POST)
        if form.is_valid():
            form.save()
            return redirect(request.META.get('HTTP_REFERER'))
        else:
            error = 'Форма не верная'
    form = ListAdd()
    context = {
        'form': form,
        'error': error
    }
    return render(request, 'main/create_list.html', context)


def purpose(request):
    cel = Purpose.objects.all()
    return render(request, 'main/purpose.html', {'title': 'Purpose', 'cel': cel})


def change_purpose(request, idp):
    d = Purpose.objects.get(id=idp)
    return render(request, 'main/change_purpose.html', {'title': 'Purpose', 'd': d})


def add_task_purpose(request, idp):
    task = Task.objects.all()
    if request.method == 'POST':
        if request.POST['task']:
            post = request.POST['task']
            day = Purpose.objects.get(id=idp)
            day.task.add(Task.objects.get(id=post))

    return render(request, 'main/add_task_purpose.html', {'title': 'Purpose', 'task': task, 'id': idp})


def create_purpose(request):
    error = ''
    if request.method == 'POST':
        form = PurposeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(request.META.get('HTTP_REFERER'))
        else:
            error = 'Форма не верная'
    form = PurposeForm()
    context = {
        'form': form,
        'error': error
    }
    return render(request, 'main/create_purpose.html', context)


def dell_purpose(request, idp, idt):
    d = Purpose.objects.get(id=idp)
    d.task.remove(Task.objects.get(id=idt))
    return redirect(request.META.get('HTTP_REFERER'))

taskmanager/main/templates/main/add_task.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <label class="form-label">Task:</label>
        <div class="mb-3">
            <select multiple id="task" name="task">
                {% for el in task %}
                    <option value="{{ el.id }}">{{ el.name }} {{ el.time}}</option>
                {% endfor %}
            </select>
            <a href="{% url 'main:create_task' %}" ><img src="{% static 'main/img/add.svg' %}" alt="Add"></a>
        </div>
        <button type="submit" class="btn btn-success">Add</button>
        {% block list %}{% endblock %}
    </form>
{% endblock %}

taskmanager/main/templates/main/add_task_list.html
{% extends 'main/add_task.html' %}

{% block list %}
    <input type="text" name="data"  size="10" required="" id="id_data">
    <a href="{% url 'main:list' %}" class="btn btn-success" role="button">List</a>
{% endblock %}

taskmanager/main/templates/main/add_task_purpose.html
{% extends 'main/add_task.html' %}

{% block list %}
   <a href="{% url 'main:change_purpose' id%}" class="btn btn-success" role="button">Purpose</a>
{% endblock %}

taskmanager/main/templates/main/add_task_week.html
{% extends 'main/add_task.html' %}

{% block list %}
   <a href="{% url 'main:change_week' %}" class="btn btn-success" role="button">Timetable</a>
{% endblock %}

taskmanager/main/templates/main/base.html
<!doctype html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
        <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
          <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
              <img src="{% static 'main/img/icon.png' %}" width="25" height="25" alt="icon">
              ControLife
          </a>
            <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'main:home' %}" class="nav-link px-2 text-dark">Home</a></li>
                <li><a href="{% url 'main:timetable' %}" class="nav-link px-2 text-dark">Timetable</a></li>
                <li><a href="{% url 'main:list' %}" class="nav-link px-2 text-dark">List</a></li>
                <li><a href="{% url 'main:purpose' %}" class="nav-link px-2 text-dark">Purpose</a></li>
            </ul>
            <div class="col-md-3 text-end">
                <button type="button" class="btn btn-light">Login</button>
                <button type="button" class="btn btn-light">Sign-up</button>
            </div>
        </header>

        <div class="container">
            {% block content %}{% endblock %}
        </div>
</body>
</html>

taskmanager/main/templates/main/change_purpose.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    {% if d %}
        <div class="alert alert-secondary" role="alert">
            <h3>{{ d.name }}</h3>
            <p>{{ d.start }}</p>
            <p>{{ d.planed }}</p>
            <hr>
            {% for t in d.task.all %}
            <p>{{ t.name }} <a href="{% url 'main:dell_purpose' d.id t.id %}"><img src="{% static 'main/img/dell.svg' %}" alt="Dell"></a></p>
            {% endfor %}
           <a href="{% url 'main:add_task_purpose' d.id %}"><img src="{% static 'main/img/add.svg' %}" alt="Add"></a>
        </div>
    {% else %}
        <p>Free <3</p>
    {% endif %}
    <a href="{% url 'main:purpose' %}" class="btn btn-success" role="button">Purpose</a>
{% endblock %}

taskmanager/main/templates/main/change_week.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <h1>Расписание <a href="{% url 'main:timetable' %}" class="btn btn-secondary" role="button">Ready</a></h1>
    <table class="table">
        <thead>
            <tr>
                {% for day in week_n %}
                    <th scope="col">{{day}}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            <tr>
                {% for i in  week %}
                <td>
                    {% if i %}
                        {% for mo in i %}
                            {% for el in mo.task.all %}
                                <p>{{ el.name }} <a href="{% url 'main:dell_task' mo.id el.id %}"><img src="{% static 'main/img/dell.svg' %}" alt="Dell"></a></p>
                            {% endfor %}
                            <center><a href="{% url 'main:add_task_week' mo.id %}"><img src="{% static 'main/img/add.svg' %}" alt="Add"></a></center>
                        {% endfor %}
                    {% endif %}
                </td>
                {% endfor %}
            </tr>
        </tbody>
    </table>
{% endblock %}

taskmanager/main/templates/main/create_list.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
    Creating a Task
{% endblock %}

{% block content %}
    <h1>Creating a Task</h1>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label  class="form-label">Task:</label>
            {{ form.task }}
            <a href="{% url 'main:create_task' %}"><img src="{% static 'main/img/add.svg' %}" alt="Add"></a>
        </div>
        <div class="mb-3">
            <label  class="form-label">Data:</label>
            {{ form.data }}
        </div>
        <p><span>{{ error }}</span></p>
        <button type="submit" class="btn btn-success">Добавить</button>
        <a href="{% url 'main:list' %}" class="btn btn-success" role="button">List</a>
    </form>
{% endblock %}

taskmanager/main/templates/main/create_purpose.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
    Create a goal
{% endblock %}

{% block content %}
    <h1>Create a goal</h1>
    <form method="post">
        {% csrf_token %}
        <label  class="form-label">Name:</label>
        <div class="mb-3">
            {{ form.name }}
        </div>
        <label  class="form-label">Task:</label>
        <div class="mb-3">
            {{ form.task }}
            <a href="{% url 'main:create_task' %}"><img src="{% static 'main/img/add.svg' %}" alt="Add"></a>
        </div>
        <label  class="form-label">Data:</label>
        <div class="mb-3">
            {{ form.planed }}
        </div>
        <button type="submit" class="btn btn-success">Add</button>
        <a href="{% url 'main:purpose' %}" class="btn btn-success" role="button">Purpose</a>
         <span>{{ error }}</span>
    </form>
{% endblock %}

taskmanager/main/templates/main/create_task.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
    Creating a Task
{% endblock %}

{% block content %}
    <h1>Creating a Task</h1>
    <form method="post">
        {% csrf_token %}
        <label  class="form-label">Task:</label>
        <div class="mb-3">
            {{ form.name }}
        </div>
        <meta charset="utf-8">
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'main/css/tpicker.css' %}">
        <script type="text/javascript" src="{% static 'main/js/tpicker.js' %}"></script>
        <label  class="form-label">Time:</label>
        <div class="mb-3">
            {{ form.time }}
            <button type="button" class="btn btn-primary" onclick="showpickers('timepkr',24)" style="width:40px;float:left;">
                <i class="fa fa-clock-o"></i>
            </button>
            <div class="timepicker"></div>
            <span>{{ error }}</span>
            <button type="submit" class="btn btn-success">Add</button>
        </div>
    </form>
{% endblock %}

taskmanager/main/templates/main/purpose.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <div class="alert alert-light" role="alert">
        <h1>Purpose</h1>
        {% if cel %}
            {% for el in cel %}
                <div class="alert alert-secondary" role="alert">
                    <h3>{{ el.name }} <a href="{% url 'main:change_purpose' el.id %}" class="btn btn-secondary" role="button">Change</a></h3>
                    <p>Start: {{ el.start }}</p>
                    <p>Plan to finish: {{ el.planed }}</p>
                    <hr>
                    {% for t in el.task.all %}
                        <p>{{ t.name }}</p>
                    {% endfor %}
                </div>
            {% endfor %}
        {% else %}
            <p>You have no goal</p>
        {% endif %}
         <center><a href="{% url 'main:create_purpose' %}" class="btn btn-light" role="button">+</a></center>
    </div>
{% endblock %}

taskmanager/main/templates/main/start.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
ControLife
{% endblock %}

{% block content %}
    <center><img src="{% static 'main/img/start.gif' %}"width="600" height="400" ></center>
{% endblock %}

taskmanager/main/templates/main/todolist.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <div class="alert alert-light" role="alert">
        <h1>{{now}} <a href="{% url 'main:change_week' %}" class="btn btn-light" role="button">Change</a></h1>
        {% for d in day %}
        {% if d.task.all %}
            {% for el in d.task.all|dictsort:"time" %}
                <div class="alert alert-secondary" role="alert">
                    <h4>{{ el.name }}</h4>
                    <p>{{ el.time }}</p>
                </div>
            {% endfor %}
        {% else %}
            <p>Nothing planned for today</p>
        {% endif %}
        {% endfor %}
    </div>

    <div class="alert alert-light" role="alert">
        <h1>List</h1>
        {% if task %}
            {% for el in task|dictsort:"data" %}
                    <div class="alert alert-secondary" role="alert">
                        <h3>{{ el.task.name }} <a href="{% url 'main:dell_list' el.id el.task.id %}"><img src="{% static 'main/img/dell.svg' %}" alt="Dell"></a></h3>
                        <hr>
                        <p>{{ el.data }} {{ el.task.time }}</p>
                    </div>
            {% endfor %}
        {% else %}
            <p>The list is empty</p>
        {% endif %}
        <center><a href="{% url 'main:create_list' %}" class="btn btn-light" role="button">+</a></center>
    </div>
{% endblock %}

taskmanager/main/templates/main/week.html
{% extends 'main/base.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}
    <h1>Расписание <a href="{% url 'main:change_week' %}" class="btn btn-light" role="button">Change</a></h1>
    <table class="table">
        <thead>
           <tr>
                {% for day in week_n %}
                    <th scope="col">{{day}}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            <tr>
                {% for i in  week %}
                <td>
                    {% for mo in i %}
                        {% if mo.task.all %}
                        {% for el in mo.task.all %}
                            <p>{{ el.name }} </p>
                        {% endfor %}
                        {% else %}
                            <p>Free</p>
                        {% endif %}
                    {% endfor %}
                </td>
                {% endfor %}
            </tr>
        </tbody>
    </table>
{% endblock %}